### ISSUE TITLE
Add support for Persistent volumes creation

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi#116]
Cluster Controller should have support for deploying cluster with Persistent volume claims. By default, the volume claims should be created using the default StorageClass, but it should be possible to define a specific storage class to be used (since it can be expected that some might choose faster disks for Kafka etc.).

**Comment by ppatierno** [comment]
This issue is related on what we have today in the cluster-controller, the support only for `emptyDir` which maps which is the `kafka-inmemory` deployment (from master).
So the cluster-controller needs a way to get information from the cluster ConfigMap in order to use an `emptyDir` or a `persistentVolume`.
Such information could be put into the `data` section of the cluster CM.

We could have one or more field with `storage`prefix : 

- `storage-type` : it could be `in-memory` (for providing `emptyDir`), `persistent` (for `persistentVolume`) and maybe `local` (referring to issue #117)
- `storage-size` : for specifying the size (`sizeLimit` for `emptyDir`, `storage` for the volume claim template)
- `storage-class` : it should be optional for specifying a storage class in case of persistent volume (it can be omitted to use the default one or when it's not needed, i.e. type=in-memory)
- `storage-selector` : it should be optional for specifying labels for persistent volume claims on selecting storages.

Another option could be using K8S/OS terminology, so explicitly saying `emptyDir` instead of `in-memory`, `persistentVolume` instead of `persistent` and so on.

@scholzj wdyt ? Any thoughts ?

**Comment by ppatierno** [comment]
We could even think about only one `storage` field with a JSON value configuring about information but if possible I would avoid JSON in this case (we need it for the metrics due to JMX exporter but don't think that we need it here).

**Comment by scholzj** [comment]
@ppatierno 
* `emptyDir` has technically nothing to do with "in-memory". It is not in-memory, it is even not completely non-persisitent. So maybe we should just call it by the volume type `emptyDir` or maybe `temp` (it is basically temporary storage).
* Persistent Volume can be probably called as a `pvc`, `volumeclaim` or `persistentvolumeclaim` ... it should be able to support everything what can be claimed.
* I actually not sure how the local volumes are provisioned. That is why I put it into separate issue :-o. It should be possible to do it either by adding `storage-type` called `local` as you suggested, so that should not be a problem.

Two questions / points:
* What exactly does the `storage-selector` do?
* I'm a bit afraid that we will have a huge flat config map with `millions` of options which will be hard to read (for humans). I/m wondering if we should create there some strucutre ... such as having field `storage` and all the fields as its children. But that would mean that we will need to have either everything in JSON or mix JSON snippets into the fields. Not sure we want to decide this in this issue.

**Comment by ppatierno** [comment]
> What exactly does the storage-selector do?

From the K8S API doc (https://v1-8.docs.kubernetes.io/docs/api-reference/v1.8/#persistentvolumeclaimspec-v1-core) you can specify some labels for asking for persistent volumes with such labels. More info even on OpenShift doc here (https://docs.openshift.org/latest/install_config/storage_examples/binding_pv_by_label.html#binding-pv-by-label-pv-with-labels)

**Comment by ppatierno** [comment]
@tombentley wdyt about this issue and on how to define the structure for storage information ?

**Comment by scholzj** [comment]
@ppatierno Thanks for the `storage-selector` explanation. Makes sense to support it. 

BTW: we should start slowly writing the docu - at least in the form of some notes documenting all these options and how to use them.

**Comment by ppatierno** [comment]
@scholzj regarding `storage-type` what do you think about : 

- `temp` (as you suggested) for the `emptyDir`
- `persistent-claim` for all claimed stuff
- `local` for a future local storage

**Comment by tombentley** [comment]
@ppatierno about how to configure it, I think we should seriously consider a CRD to support configuring this. We are only going to be adding more config to the cluster controller as we progress, and when we switch to using a CRD all the configs written in tests etc will need to be rewritten as the custom resource. 

As for the rest of the issue, it seems to make sense; I've not got enough expereience with this stuff in k8s to make a more useful comment.

**Comment by ppatierno** [comment]
@tombentley but using CRD means having storage description outside of the cluster CM so we should deal with a different YAML file which should be deployed before the cluster CM one in order to have the cluster-controller finding the CRD while getting configuration from the cluster CM.

**Comment by tombentley** [comment]
Sorry I wasn't too clear: what I meant was that the cluster CM should be a cluster CRD.

**Comment by ppatierno** [comment]
@tombentley so as discussed offline let's investigate on CRDs usage for the future (even about the fabric8 support) but let's stay using JSON as value for configuring the storage information.
It means that the cluster CM will have just one field named `storage` with a JSON structure which could be something like this : 

`
{ 
type= temp | persistent-claim | local, 
size= <size>, 
class= <storage-class>, 
selector= { <label1>=<value1>, .... <labeln>=<valuen> }
}
`

Where : 

- `type` is mandatory (`temp`, `persistent-claim` or `local` as values)
- `size` is optional
- `class` makes sense only if type is `persistent-claim` but it's optional and without it, the default provisioner is used
- `selector` makes sense only if type is `persistent-claim` and it's optional. Its value should be a JSON map with label=value for the `matchLabels` field which will be used at Kubernetes level during the persistentVolumeClaim creation.

@tombentley @scholzj wdyt ?

**Comment by tombentley** [comment]
Using a single key with a json value is fine with me. I'd be interested if we can write down a OpenAPI Schema (https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#schema-object) for the value (even though we won't actually use the schema at this point), as doing that could make a future move to CRD less painful as the value would then map directly. 

We should open a separate issue for investigating CRD (what it buys us technically as well as Kubernetes version constraints etc).

**Comment by ppatierno** [comment]
Actually we need two keys in the cluster CM for Kafka and Zookeeper, so something like `kafka-storage` and `zookeeper-storage`.

**Comment by scholzj** [comment]
@ppatierno +1. Makes sense to have `kafka-storage` and `zookeeper-storage` with the structure as described above. Maybe we can use `temporary` instead of `temp` since the other name is also long. But that is just a very very minor detail.

**Comment by ppatierno** [comment]
@scholzj If you could see my code (but it's not committed so just on my laptop) you would see it defined as "temporary" (I changed my mind but not updating the issue) ... you can read in my mind !

**Comment by scholzj** [comment]
@ppatierno reading mind on such a long distance would be black magic ... this is just awesome teamwork! :-D

**Comment by scholzj** [comment]
@ppatierno Are we still missing something for this issue? I think it can be closed, or?

**Comment by ppatierno** [comment]
@scholzj I haven't added the "selector" handling yet. I was wondering if a new issue could be better for this. Wdyt ?

**Comment by scholzj** [comment]
@ppatierno Ah, ok ... I will leave that up to you to decide.

**Comment by ppatierno** [comment]
Closed by #136
