### ISSUE TITLE
Do update when add is called on existing cluster

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi#124]
When the "add" event is triggered on existing cluster (for example during controller restart) it is currently ignored. We should instead in such situation change the event to "update" and do a cluster update. This might allow to detect faster changes to the underlying ConfigMaps.

**Comment by scholzj** [comment]
@ppatierno @tombentley I guess this will be resolved with #171 or? When we call reconcile for each Watch event it should be handled.

**Comment by tombentley** [comment]
That's my expectation, yes

**Comment by scholzj** [comment]
Ok. I will assign it to @ppatierno so that he can close it when he is finished with it.

**Comment by ppatierno** [comment]
closed by #263
