### ISSUE TITLE
Work accross namespaces

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi#125]
Currently, the Cluster controller works only within one namespace. We should make it possible to run a single Cluster Controller but deploy clusters into multiple namespaces. In the ideal case, we should make it optional to be able to work with different security levels (cross namespace access will need more right than staying within the namespace).

**Comment by tombentley** [comment]
Currently the cluster controller takes the namespace to watch and reconcile from its environment. Should it simply be configured with a list of such namespaces from the environment?

**Comment by scholzj** [comment]
Yeah, interesting question. My idea was more or less following:
- If no namespace specified, look for config maps in all namespaces
- If namespace specified, use only the selected namespace

Having a list of namespaces might be useful. But it can be replaced by having controller per namespace. I would say that if it can be implemented for free, why not. If it needs some effort, lets wait for some real use case.

What I thought would be useful is having a blacklist for namespaces to ignore in the "all namespaces" approach ... but I guess we should ignore it until we have a real usecase.

**Comment by ppatierno** [comment]
Not an expert of how the service broker works but as far as I understood, when we'll add the support for the service broker, we'll have the API implemented in the cluster controller which in that case should be able to deploy and watch a cluster in a different namespace where the controller is running. 
Is my understanding right ?

**Comment by scholzj** [comment]
I do not think the Service Broker is relevant to this. The service broker will get some kind of HTTP/REST inputs AFAIK. Not watch for ConfigMaps

Ultimately this is only about the watch ... the watch needs to watch for ConfigMaps ... once it gets the config map, the cluster will be deployed into the same namaspace as the configmap is in.

**Comment by ppatierno** [comment]
Yes the ConfigMap to watch and the related deployed cluster will be in the same namespace but the cluster controller could run in a different one right ? It's what we are saying or ?
So in relation to the Service Broker, the cluster controller should be already deployed in a namespace making available itself to the Service Broker through HTTP/REST API.
This is the reason why I was thinking that this feature impact how we'll work with the Service Broker.

**Comment by tombentley** [comment]
With [this API](https://github.com/kubernetes/kubernetes/pull/48051) I believe we could detect when we were running with permissions to watch+list CMs in all namespaces and in that case we could use a single watcher for multi-namespace support. Lacking that we need a watcher for each namespace.

**Comment by scholzj** [comment]
@tombentley You mean to setup a watch for all namespaces and filter the _enabled_ namespaces afterwards inside our code? That should work fine ... but I'm not sure we should overcomplicate it given we have no real use case for _some namespaces_ ... so pick one solution and go for it.

**Comment by tombentley** [comment]
This has been done.
