### ISSUE TITLE
Watch partitions

### ISSUE THREAD

**Issue by tombentley** [strimzi/strimzi#137]
The topic operator needs to know about changes in #partitions and replication factor so it can keep the config map up to date. We can do that by setting a zookeeper data watch on `/brokers/topics/${topic}`.

**Comment by tombentley** [comment]
This should basically be quite similar to how we're handling changes in topic config via the `TopicConfigsWatcher`.

**Comment by ppatierno** [comment]
We agree on addressing only the partitions side in this issue. The separated #191 issue will address the replication factor problem.

**Comment by ppatierno** [comment]
Closed by #195
