### ISSUE TITLE
Prevent multiple configmaps trying to manage the same topic

### ISSUE THREAD

**Issue by tombentley** [strimzi/strimzi#139]
Because the rules for valid topic names differ from the rules for config map names, the configmap supports a `name` key to give the name of the topic. This opens the possibility that two configmaps could both try to manage the same key. We should prevent this.

**Comment by tombentley** [comment]
There are actually several name-based issues tied up in this, and it's difficult to deal with them piecemeal without having some bigger picture of how this should work. So let me spec something out here. 

The starting facts are:

1. A valid configmap name must match the regex `[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*` and be shorter than 253 characters. See also: [this](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/architecture/identifiers.md)
2. A valid topic name must match the regex: `[a-zA-Z0-9._-]*`, be shorter than 250 chars, and be neither `.` nor `..`.
3. A ConfigMap can supply a `data/name` key, which must be a valid topic name, otherwise the ConfigMap's `metadata/name` is used as the topic name. 
4. A user could thus change the `data/name` key (this is #140)
5. But similarly a user could change the ConfigMap's `metadata/name`. The ConfigMap's `metadata/uuid` could be used to disambiguate such a change from a delete+add.
6. Kafka doesn't currently offer an API for changing a topic's name, but it could do in the future.

From 1 and 2 we can observe that the number of syntacitcally legal names on each side is different, so it is logically impossible to construct a perfect mapping/encoding. In other words we're just looking for something that's good enough in practice. Also notice that a user could create a ConfigMap with `metadata/name` "foo" and `data/name` "bar" and then create a topic "foo": In this case the controller can't use the obvious name, "foo". 

I think that the topic controller should not go about renaming things to try to tidy up a user's messy naming, but should report an error for an administrator to fix, and in the meantime ignore a topic or configmap. To make this work in practice we need:

1. To make the topic controller understand CM identity via its UUID (so it doesn't treat a CM rename as a delete+add).
2. Have a way of generating a legal CM name given a topic name.
3. Ensure (via testing) the TC logs errors (and produces Warning events) when it cannot process a CM or topic change, and that once the cause is addressed the TC again reconciles changes.

Elaborating on item 2, operationally it is very helpful if the configmap names bear some resemblance to the topic name that they pertain to. How about this algorithm:

1. If the topic name is a legal configmap name then we use the topic name.
2. Otherwise we construct a name by iterating each character, forming a string, `prefix`:
    * If the character is legal in this position we append it to a `prefix`
    * If the character is an uppercase letter we append its lowercased version to a `prefix`
3. We form the name from `prefix + "---" + hex(sha1(utf8(topicName))`. If this is longer than 253 character we truncate `prefix` sufficiently to make it fit (a hex-encoded sha1 is 40 chars).

This will ensure that configmap names do bear some resemblance to the corresponding topic name, and also ensure the probability of collisions is practically zero.

Thoughts, @ppatierno @scholzj ?

**Comment by tombentley** [comment]
Here are some examples of that the encoded names would look like in a few cases:

Topic name | ConfigMap name
--------------|----------------------
foo         | foo
Foo         | foo---201a6b3053cc1422d2c3670b62616221d2290929
FOO         | foo---feab40e1fca77c7360ccca1481bb8ba5f919ce3a
foo.bar     | foo.bar
foo.BAR     | foo.bar---2b539a9cb49ce7280d7ebfb93b08540a6535ba35
foo-bar.baz | foo-bar.baz
__foo       | foo---117282ae03235561f215ee101800b2d5b3609f7
foo__       | foo---47318fcc6fa7f277565de829dbd878e03530e078
foo__bar    | foobar---423126006221ca9092992ce14121ee0a3eaed346
--foo       | foo---5a5af07607cb6064c0183648a704188a457b1eb6
foo--       | foo---b16c222dbf36b52253b205d0132eab9d7d879907
foo--bar    | foo--bar
..foo       | foo---cab6ff58f3d59a9f69aaa8c19603f7ce9bb34056
foo..bar    | foo.bar---4683128189ed6ca9d78cb034fa97f327e46d7465
foo..       | foo---ab2e4e62f3b8c288495eb2616ee2cd678f83a63f
foo.-bar    | foo.bar---4f4325245861ad879d835e7fca95145c2f8c5eb8
foo-.bar    | foo-bar---6ba1b74e7c34254171fabf7cdfbba9936356e940
\-           | 3bc15c8aae3e4124dd409035f32ea2fd6835efc9
\--          | e6a9fc04320a924f46c7c737432bb0389d9dd095
\...         | 6eae3a5b062c6d0d79f070c26e6d62486b40cb46
\-.          | d6aee8987a388b8b4c590e42011c8a18286f7ca8
\.-          | 5166aaeb81d80edb1b34f9550e3c5cdf4edfe8a7

I guess it might be slightly nicer/more obvious if the separator was `.sha1-`

**Comment by tombentley** [comment]
In practice, it appears that it's not possible to change a ConfigMap's name

```
$ oc patch cm example-topic-cm -p "$(cat topic-controller/resources/example-patch.yaml)"
Error from server (BadRequest): the name of the object (example-topic-cm2) does not match the name on the URL (example-topic-cm)
```

Which at least removes some possible test scenarios.

**Comment by tombentley** [comment]
> Also notice that a user could create a ConfigMap with metadata/name "foo" and data/name "bar" and then create a topic "foo": In this case the controller can't use the obvious name, "foo".
>
> I think that the topic controller should not go about renaming things to try to tidy up a user's messy naming, but should report an error for an administrator to fix, and in the meantime ignore a topic or configmap.

Given than you can't rename a CM, the problem to solve here is how can an admin fix this situation? To make room for the new topic "foo" they will have to change the name of the CM "foo", but if they delete it that will delete the topic "bar". I guess to allow them to do this we need a way for them to stop the controller from managing the CM "foo", then they can delete it safely (without the topic "bar" being deleted), and create a new CM called "bar". Ideally they also want a way to express 'Don't try to merge this new CM with the topic "bar", just update it with the configuration of the topic'.

From this we derive a couple of new requirements:

1. The ability to have a CM that's being managed and to make it unmanaged without deleting the corresponding topic.
2. The ability to create a CM with the option to set its content from an existing topic. 

Corresponding ideas for implementation:

1. Could be done using selectors, so the controller will watch those CM with labels matching `strimzi.io/kind=topic,strimzi.io/managed!=false`. In any case I guess we needed to define the semantics around CM changes which cause CM to match/unmatch the selector.
2. The obvious way here is to use an empty CM data to denote this.

Thoughts please @scholzj @ppatierno

**Comment by scholzj** [comment]
I'm not sure what kind of ehavior would the `strimzi.io/managed=false` label trigger. Would it make you ignore the ConfigMap? Wouldn't you then create a new one? Or will it be somehow used to say "don't touch the topic names in this config map"?

Anyway, if renaming the ConfigMap is not possible (which makes sense) then it is hard to work around it. Depending on how you treat two config maps for the same topic, you can also say that to rename the config maps one should do *create new* & *delete old* instead of *delete old* & *create new*. But I think your plan was to not support duplicate ConfigMaps.

**Comment by tombentley** [comment]
> I'm not sure what kind of ehavior would the strimzi.io/managed=false label trigger. Would it make you ignore the ConfigMap? Wouldn't you then create a new one? Or will it be somehow used to say "don't touch the topic names in this config map"?

The idea is that the sequence of operations "strimzi.io/managed=false", "delete CM" would allow the CM to be deleted without deleting the topic. You could then create a new one CM (with the correct name, and with just a `data.name`), and the new one's `data` would get populated according to the topic. It is, in effect, a poor-man's rename.

> you can also say that to rename the config maps one should do create new & delete old instead of delete old & create new. But I think your plan was to not support duplicate ConfigMaps.

I guess we could make that work iff we could rely on k8s putting both delete and create in the same invocation of the CM watch. That way we could determine that it was (in effect) a rename and avoid the usual path which would result in a deletion (or an error, depending on which it processed first). But I don't think k8s provides any such atomicity, does it?

We have this corner-case because we let users create a CM with an arbitrary name, which can collide with a name we later generate for a newly created topic. We could avoid the need for either of the above rename-like operations by either:

* Requiring people only create CMs with metadata.name consistent with its data.name. (This option is not ideal because often it will be hard for people to figure out what the CM name should be).
* Making the name generation depend on the set of existing CM names. (This option is not ideal because it makes the controller more stateful, and the name generation is no longer purely a function of topic name).

**Comment by tombentley** [comment]
> I guess we could make that work iff we could rely on k8s putting both delete and create in the same invocation of the CM watch.

We could also do this using timers within the controller, so when we see a create or delete we wait N seconds for a matching delete/create before proceeding. But that's seriously nasty!

**Comment by scholzj** [comment]
> The idea is that the sequence of operations "strimzi.io/managed=false", "delete CM" would allow the CM to be deleted without deleting the topic. You could then create a new one CM (with the correct name, and with just a data.name), and the new one's data would get populated according to the topic. It is, in effect, a poor-man's rename.

This sounds strange to me. 
* First issue might be the synchronization here - you will need to make sure these eventy are properly synchronized.
* Second I'm not sure what would it exactly mean to stop managing the topic. You would need to maintain some list of "unmanaged" topics which would be fine. But than you would need to somehow "start managing" the topic again. This could be manual creation of the Config Map by user. But it sounds strange that this will be done only from the Kafka side.

I do not know ... maybe we should't care about this now too much. Just map the naming, make sure to avoid the conflicts and that is it. And start dealing with things like "how to rename config map" only if someone really needs it. I think we should also start the docu with a clear recommendation how to use it. 

When will we have the aggregated API server to make these things easier? :-o

**Comment by tombentley** [comment]
Yeah, I agree that I'm obsessing about a corner case here (given that neither end supports renaming anyway). It's only really a problem if the user creates a CM with a name which the user later wants to use as a topic name. Because of the need to sanitize topic names, we should in any case be making a recommendation to users on how they name their topics and CMs. Such a recommendation would go a long way to avoiding this problem.

If we're agreed that this is the best course of action, I think what remains to be done is:

> 3. Ensure (via testing) the TC logs errors (and produces Warning events) when it cannot process a CM or topic change, and that once the cause is addressed the TC again reconciles changes.

**Comment by ppatierno** [comment]
@tombentley @scholzj I have to admit that even after reading this issue a couple of times the conclusion isn't so clear to me. Is there a document where the "logic" applied by the topic controller is described ? Such a document could be useful to the user as well ...

**Comment by tombentley** [comment]
@ppatierno the summary is:

1. Trying to create a 2nd CM to manage a single topic will result in an k8s warning event, and the 2nd CM will basically be ignored. 
2. Neither k8s nor kafka supports renaming (of CM, topics respectively). Additionally the controller will detect changes to a CM's data.name, create a Warning event and ignore any other changes to the CM. 
3. It won't be possible to delete a CM and create another one for managing the same topic without deleting the topic (so chose your names carefully).
