### ISSUE TITLE
Test `Session`

### ISSUE THREAD

**Issue by tombentley** [strimzi/strimzi#141]
Some code exists for reconfiguring the topic controller when its configmap changes, but it's untested and could probably be simplified.

**Comment by scholzj** [comment]
Do we want to configure it though the config map? Wouldn't it be easier to configure it through the environment variables? The reloading of configuration on the fly seems to be a bit wasted effort given how much we invest to make sure it deals well with restarts. And that would be probably the only value we get from using ConfigMap. Or?

**Comment by tombentley** [comment]
The ConfigMap way seemed like a good idea at the time, but it is true that currently we could configure everything we need from the environment. 

In any case, the point is that there is some non-trival code which configures things from some config which is currently untested. It is also responsible for correctly shutting down the controller and the associated connections (which is important for not leaving things in an inconsistent state). It's about the only significant piece of code which lacks test coverage.

**Comment by scholzj** [comment]
Ok, valid point. What I don§t like in particular about the config map is that I'm not sure we want to end up with configmap which is taken by controller which creates config map taken by another controller. It was just the first think which came to my mind when I saw this issue.
