### ISSUE TITLE
Add readiness and liveness probe to Cluster controller

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi#143]

**Comment by ppatierno** [comment]
I'm thinking about exposing an HTTP endpoint from the cluster-controller (maybe using Vert.x Health Checks component for that).

Regarding the readiness probe, we know that the cluster-controller is ready when the watcher for the ConfigMap is created successfully so it's able to watch for cluster CM to interact with.

Regarding the liveness probe I have two different ideas (the first one is simpler than the other) : 

1. when the liveness is invoked by K8S/OS, the health check just verify that the Kubernetes client (from fabric8) can interact with the K8S/OS cluster so with the server API (i.e. making a "dummy" request about namespace or pods or services or ...).
1. because the cluster-controller is really working if the watcher on ConfigMap is working as well, then we should need a way to check that it's true. Maybe, the health check could create a "dummy" ConfigMap with something like `kind=health` in order to interact with the ConfigMap watcher and replying OK if such a CM is created and deleted by cluster-controller otherwise KO. We could need a communication channel between the watcher and the health check (maybe Vert.x Event bus, maybe something simpler).

Of course the second option produce more Kubernetes "traffic" and creation/deletion of resources needed just for health checking but at least proves that the CM watcher is really working.

The issue #151 is about heath checking the topic-controller but it has to check more other things (i.e. Zookeeper and Kafka connections, ...).

@scholzj @tombentley any thoughts ?

**Comment by scholzj** [comment]
Yeah, the readiness could be after the watch is setup. In theory you could setup some check that reconciliation is successfully passing etc. 

For the liveness - you should normally just return 200 OK. No need to anything elaborate. I should just say that the image is up and running ind is able to respond.

**Comment by ppatierno** [comment]
But if for any reasons the CM watcher isn't working, it's not true that the cluster-controller is able to respond to the requests (new cluster CM is created). We can have the image up and running but it's useless; the health check is always OK but the cluster-controller isn't really "live" imho.

**Comment by scholzj** [comment]
That should be IMHO a part of the readiness probe ... the app will be alive, only not ready. I don't think we should create any artificial config map to test it. That can trigger some monitorings etc.

**Comment by ppatierno** [comment]
@scholzj if the configmap watcher is created it should mean that the cluster-controller is able to get CM changes ... so it's ready and can receive "requests". At this point the readiness isn't raised anymore. After that the liveness probe enters into action to check that after 1 min, 2 min or ... the watcher is still working. 

@tombentley checking the reconciliation could be an addition (making sure that the Vert.x timer side isn't crashed for any other reason) but it doesn't interact with the watcher.

From my point of view, the cluster-controller is working properly if it can detect a cluster CM (creation, update, deletion) otherwise the controller needs to be restarted.

**Comment by scholzj** [comment]
AFAIK the readiness probe is called periodically ... it is for example used to add endpoints for services etc. It should not be one off thing.

**Comment by ppatierno** [comment]
@scholzj yes sorry you are right but thinking more ...

When a readiness probe fails, K8S stops to send requests to a pod behind a service for example until the readiness probe returns ok. It doesn't restart the pod in any case afaik.
When a liveness probe fails, the K8S restarts the pod : isn't a problem with the watcher a condition which should trigger a restart ?
I mean our cluster-controller isn't a simple "service" (not a K8S one :-)) listening for requests ... it's interacting directly with the K8S API.

**Comment by scholzj** [comment]
Yeah ... we might not need the readiness probe so much right now - although it might be useful for monitoring.

**Comment by ppatierno** [comment]
so at this point it seems that having an HTTP endpoint active only when the ConfigMap watcher is created successfully is enough for now.
In any case I'll expose readiness and liveness on two different HTTP paths (i.e. `/health` and `/ready`) but just returning OK for now but leaving opened the door for having different logics behind them.

**Comment by scholzj** [comment]
Ok, sounds good to me.

**Comment by ppatierno** [comment]
Closed by #185
