### ISSUE TITLE
Add application domain to labels

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi#148]
This issue is about adding the "strimzi.io" domain for labels used in every K8S/OS resources related to topic and cluster controller.
It means that : 

- `kind` label will be `strimzi.io/kind`
- `app` label won't be necessary anymore because now we have a domain in the label for representing the application when it comes to watch resources from "strimzi"

**Comment by scholzj** [comment]
@ppatierno @tombentley I think this has now been implemented in both CC and TC and can be closed, or?

**Comment by ppatierno** [comment]
@scholzj fine with me on the CC side.

**Comment by tombentley** [comment]
This is done in the topic-controller2 branch. I guess we should wait until that's merged into cluster-controller before actually closing this.

**Comment by scholzj** [comment]
Ok, in that case lets assign it to you so that you can close it after merging.
