### ISSUE TITLE
Cluster controller creates Zookeeper metrics ConfigMap but they are disabled through JMXDISABLED

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi#201]
Running the master I noticed that executing : 

`oc exec -it my-cluster-zookeeper-0 -- curl http://localhost:9404`

the metrics wasn't exposed anymore (the HTTP address ins't accessible).
Taking a look at this commit f1daef48dfe68c88a570498dd085efd13a312476 , it seems that the `JMXDISABLED` env var is true in order to disable Zookeeper metrics.
In any case the cluster controller is creating the metrics configmap if the related cluster  configmap contains the `zookeeper-metrics-config` field. I think that this behaviour is inconsistent because the user expects to have metrics enabled.
For this reason, if we want to keep metrics disabled through `JMXDISABLED` env var, we should disable Zookeeper metrics from the cluster controller in some way as well, at least providing a warning that metrics are disabled and that the `zookeeper-metrics-config` will not have any effect.
@scholzj wdyt ?

**Comment by scholzj** [comment]
@ppatierno We should probably just enable it, or? You did the metrics ... do we need to enable / disable it conditionally? IIRC we decided to enable the metrics all the time and only the user configuration is optional, or? So we should probably just set it to `TRUE`.

**Comment by ppatierno** [comment]
@scholzj what was the rational for disabling metrics when you did the commit. I'm quite sure you had a good reason for doing that. For me the metrics should be enabled by default as we agreed leaving the user the possibility to update the config.

> So we should probably just set it to TRUE.

Do you mean setting it to FALSE :-) ... it's JMXDISABLED

If you are ok I can do that coming back to the initial metrics situation.

**Comment by scholzj** [comment]
> What was the rational for disabling metrics when you did the commit.

This is a commit from October. At that time we didn't had metrics yet. So that is why we disabled it. You added the metrics only later. What surprised me that it didn't got noticed earlier. But we probably focused on Kafka metrics more than on Zookeeper.

> Do you mean setting it to FALSE :-) ... it's JMXDISABLED

Yeah, my fault. I meant `FALSE` of course.

**Comment by ppatierno** [comment]
What I remember is that while implementing the metrics I always tested the Kafka and Zookeeper ones using `curl` on a pod for accessing the `http://localhost:9404`. I did the same while developing metrics support in the cluster controller. It's strange ... 
Btw I'm going to re-enable them, just deleting such `JMXDISABLED` set. I don't think we need having that and set it to FALSE

**Comment by scholzj** [comment]
Yeah, go for it.

**Comment by ppatierno** [comment]
Closed by 7f979460a25c1f123cc8d9c028a6fff777bc9156
