### ISSUE TITLE
operationType seems to be always `create`

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi#210]
`operationType` in seems to be always `create`. In all cluster operations. Thjis results in incorrect log messages. See for example:
https://github.com/strimzi/strimzi/blob/02d24989137420537423c01899294aa603dd80b9/cluster-controller/src/main/java/io/strimzi/controller/cluster/operations/cluster/KafkaClusterOperations.java#L45

@tombentley Do you remember what was your original intention with this?

**Comment by tombentley** [comment]
@scholzj this got fixed during the CC refactoring; the `AbstractClusterOperations.execute()` now takes an `operationType` parameters, and suitable arguments are being passed.

**Comment by scholzj** [comment]
Yeah, I agree, I remember reviewing the fix, we just didn't closed this issue (until now).
