### ISSUE TITLE
Renaming AbstractCluster and related operations hierarchy

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi#233]
Adding the topic controller deployment from the cluster controller #119 some classes like `AbstractCluster` and `AbstractClusterOperations` could not make sense anymore because topic controller is not a cluster.
With this issue I'd like to trace the classes that should be renamed and then opening a PR for that.

In order to use the `CompositeOperation` class, a class derived from `AbstractCluster` is needed but in the topic controller case it's not a "cluster", so a better name for `AbstractCluster` is needed (i.e. `AbstractComponent`). At same time, the `CompositeOperation.getCluster` doesn't make sense anymore and a `CompositeOperation.getComponent` could be better.
The returned value is a `ClusterOperation` which could be renamed as `ComponentOperation` having a `component` field instead of the `cluster` one (and the related getter method). At same time the `diff` field as `ClusterDiffResult` today could be something like `ComponentDiffResult`.

The `AbstractCluster` class should not have the `cluster` field anymore for identifying the name of the cluster but a name of the component instead. Because the `setLabels` makes still sense for real clusters so setting the "strimzi.io/cluster" label but from the component name instead I propose to have the current `AbstractCluster` renamed as `AbstractComponent` but a new `AbstractCluster` in the middle for allowing to set such a label which is specific for clusters (Kafka, Zookeeper, ..) so that the hierarchy should be for example : `AbstracComponent` -> `AbstractCluster` -> `KafkaCluster`.

The `AbstractClusterOperations` should be renamed as `AbstractComponentOperations` and the `clusterType` used inside should be a `componentType`.

**Comment by tombentley** [comment]
This has been fixed.
