### ISSUE TITLE
Factoring out an utility method for Env vars to Map conversion

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi#251]
There is the need for converting the Env Vars from a Kubernetes resource (Statefulset, Deployment, ...) to a Map in different parts of the cluster controller using the following instruction : 

`Map<String, String> vars = dep.getSpec().getTemplate().getSpec().getContainers().get(0).getEnv().stream().collect(Collectors.toMap(EnvVar::getName, EnvVar::getValue));`

We could factor out an utility method for this.

**Comment by scholzj** [comment]
@tombentley @ppatierno I have the feeling that we did this in some PR as part of some other changes (I remember we had a discussion whether the method should be `getEnvironment` or `getEnvVar`). Do we still need this or can this be closed?

**Comment by ppatierno** [comment]
@scholzj yes I remember that @tombentley did that.
