### ISSUE TITLE
Pod readiness checks should have configurable timeout values

### ISSUE THREAD

**Issue by bbrowning** [strimzi/strimzi#272]
In some environments (Travis CI, in my case), it can take longer than the hardcoded 60 seconds for the zookeeper and/or kafka pods to become available. This may be due to network slowness in downloading the container images or just general slowness of the cluster.

It would be great if these values were configurable in the Kubernetes/OpenShift yml definitions.

**Comment by scholzj** [comment]
What version of Strimzi are you using? 0.1.0? Or the master which is using the operator approach? In both cases it should be possible to configure the initial delay and timeout. It is just a bit cryptically named as _healthcheck_.

In 0.1.0, you can use following template parameters to configure it:
- `ZOOKEEPER_HEALTHCHECK_DELAY`
- `ZOOKEEPER_HEALTHCHECK_TIMEOUT`
- `KAFKA_HEALTHCHECK_DELAY`
- `KAFKA_HEALTHCHECK_TIMEOUT`

In master, you can specify it in the ConfigMap in these fields:
- `kafka-healthcheck-delay`
- `kafka-healthcheck-timeout`
- `zookeeper-healthcheck-delay`
- `zookeeper-healthcheck-timeout`

These fields are used to set the ;initialDelaySeconds` and `timeoutSeconds` settings in ReadinessProbe and LivenessProbe.

**Comment by ppatierno** [comment]
Hi @scholzj I guess that @bbrowning is referring to the 60 secs that we have hardcoded here : 

https://github.com/strimzi/strimzi/blob/master/cluster-controller/src/main/java/io/strimzi/controller/cluster/operations/cluster/KafkaClusterOperations.java#L143

If pulling image from Docker repo takes more than that, it fails. Or ?

**Comment by scholzj** [comment]
Hmm, ok. Maybe we can actually use the `kafka-healthcheck-delay` / `zookeeper-healthcheck-delay` timeouts here as a basis for some calculation (e.g. 2*`kafka-healthcheck-delay`), because these are obviously kind of connected together.

**Comment by bbrowning** [comment]
I am deploying from Strimzi master and referring to the hardcoded 60 seconds linked above as well as when waiting for the ZK pods to come up. Travis can be a bit slow when running OpenShift clusters and even when I pre-emptively `docker pull` the strimzi images ahead of time, it can still take more than 60 seconds for the ZK pods to be ready in a Travis job.

I'm not sure if these timeout values should be also tied to the K8s readiness/liveness values. I don't really want a 2-3 minute delay before K8s marks the pod as ready after it comes up, which is what would happen if I increased the `*-healthcheck-delay` values substantially. Unlike K8s, which doesn't start the clock until after the container image is pulled and the pod started, Strimzi starts its timeout clock as soon as it sees the StatefulSet was created successfully. Any timeout value used to then check for pod readiness has to be large enough to account for network speed of pulling the image the first time as well as general K8s delay in scheduling the pod, depending on how busy the cluster is.

Alternatively, instead of being configurable, the timeout could be set to say 10 minutes or something similarly high? When the ZK readiness probe times out things never recover, even during Strimzi's reconciliation. So, it would be better to err on the side of waiting longer rather than timing out prematurely.

Here's a gist of the strimzi logs when zookeeper times out - https://gist.github.com/bbrowning/c7946ca5256531938d932db2601311af . In my case Strimzi times out waiting for the ZK pods but they do eventually come up successfully. There's perhaps a second bug shown here where you see the NPEs thrown when attempting to reconcile the Kafka cluster after a ZK pod timeout.

**Comment by scholzj** [comment]
Ok, thanks a lot for the explanation .You are right that binding it to the healthcheck delay doesn't make sense because they start at different point. At the same time, I don't think hardcoding it to some long timeout like 10 minutes is a good idea, because it could delay problem detection in regular environments. So I agree that we should make this configurable.

The NPE and the fact that it actually never recovers from the expiration while the ZK is being created is is something introduced by #171 - before the reconciliation would have taken this cluster and recovered it. It should be fixed probably with #264 which covers this kind of situations (although it expects that they happen by operator mistake or something like that).

**Comment by scholzj** [comment]
I opened a PR #276 for this. I will merge it after it passes the review.

**Comment by bbrowning** [comment]
Great - thanks for the quick fix!
