### ISSUE TITLE
Unify configuration between CC and TC

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi#282]
Currently, the TC and CC has two different ways of configuration. CC accepts values in MS only. TC accepts values with time unit. We should consider unifiying this. Unfortunately, after the 0.2.0 it would break the compatibility. So we should maybe do it rather sooner than later.

**Comment by tombentley** [comment]
Which of the two styles do we want to consolidate on?

**Comment by scholzj** [comment]
I think that the CC style requires less effort and can cause less problems. But I'm quite flexible.

**Comment by ppatierno** [comment]
My inclination is to use the CC way without any timeunit in the configuration String but just using ms.

**Comment by scholzj** [comment]
@ppatierno Too late ... this should have been closed by #284

**Comment by ppatierno** [comment]
@scholzj but the #284 went into the direction I like :-)
