### ISSUE TITLE
cluster-controller doesn't respect the storage config for the storageclass.

### ISSUE THREAD

**Issue by jihed** [strimzi/strimzi#317]
Hello,

I am using the version 0.2.0 to deploy my cluster kafka on gcp.
I have four types of storage class:
oc get sc 
NAME                     TYPE
ssd                      kubernetes.io/gce-pd   
ssd-xfs                  kubernetes.io/gce-pd   
standard                 kubernetes.io/gce-pd   
standard-xfs (default)   kubernetes.io/gce-pd 

I wanted to update my cluster kafka (kafka and zookeeper) to use the ssd instead of the default:
I updated the configmap as :
'{ "type": "persistent-claim", "size": "1Gi","class": "ssd-xfs",  "delete-claim": false }' 

Results:

oc get pods 
NAME                                           READY     STATUS    RESTARTS   AGE
my-cluster-kafka-0                             1/1       Running   0          19h
my-cluster-kafka-1                             1/1       Running   0          19h
my-cluster-kafka-2                             1/1       Running   0          19h
my-cluster-topic-controller-3762949634-9vk2f   1/1       Running   0          19h
my-cluster-zookeeper-0                         1/1       Running   0          6m
my-cluster-zookeeper-1                         1/1       Running   0          6m
my-cluster-zookeeper-2                         1/1       Running   0          6m
my-cluster-zookeeper-3                         1/1       Running   0          6m
my-cluster-zookeeper-4                         1/1       Running   0          6m
strimzi-cluster-controller-957019711-x8pdh     1/1       Running   0          20h
strimzi-topic-controller-3745641952-rlr97      1/1       Running   0          19h

oc get pvc 

NAME                          STATUS    VOLUME                                     CAPACITY   ACCESSMODES   STORAGECLASS   AGE
data-my-cluster-kafka-0       Bound     pvc-b83d9641-26c6-11e8-b555-42010a840009   1Gi        RWO           standard-xfs   19h
data-my-cluster-kafka-1       Bound     pvc-b84111eb-26c6-11e8-b555-42010a840009   1Gi        RWO           standard-xfs   19h
data-my-cluster-kafka-2       Bound     pvc-b844a856-26c6-11e8-b555-42010a840009   1Gi        RWO           standard-xfs   19h
data-my-cluster-zookeeper-0   Bound     pvc-7a228bce-26c6-11e8-b555-42010a840009   1Gi        RWO           standard-xfs   20h
data-my-cluster-zookeeper-1   Bound     pvc-7a25e39a-26c6-11e8-b555-42010a840009   1Gi        RWO           standard-xfs   20h
data-my-cluster-zookeeper-2   Bound     pvc-7a2d1984-26c6-11e8-b555-42010a840009   1Gi        RWO           standard-xfs   20h
data-my-cluster-zookeeper-3   Bound     pvc-94089757-276b-11e8-b555-42010a840009   1Gi        RWO           standard-xfs   19m

This is not what we expect from the configmap. any thought ?

Regards,

**Comment by scholzj** [comment]
> I wanted to update my cluster kafka (kafka and zookeeper) to use the ssd instead of the default

Does that mean that your cluster was already running, and only than you changed the storage class? The way it works right now is that you cannot change the storage configuration once the cluster is deployed because it would cause a data loss. So the only way to do this is to delete the cluster and create a new one with the correct storage class. You should see some warning message in the cluster controller logs.

**Comment by jihed** [comment]
Thanks Jakub, Awesome job !
