### ISSUE TITLE
Add Memory and CPU requests and limits for the Cluster Controller deployment YAML files

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi#326]
Currently the YAML files for deploying Cluster Controller do not set and CPU and Memory limits / requests. We should probably set some reasonable defaults.

**Comment by tombentley** [comment]
If we're allowing to set limits and requests, it might make sense to allow configuration of the Kafka heap size too. Right now I think it defaults to 1G. It would be a shame to be able to use lots more memory than that but be forced to use it for page cache. Likewise a memory limit of less than that would end in disappointment.

**Comment by scholzj** [comment]
@tombentley That is what we have #328 for. It didn't fit into the current sprint anymore. We will need to come up with some reasonable default for the JVM / heap, since we need users to configure it, but still leave some space for the disk cache. For Zookeeper and Connect I would assume that we can just derive JVM memory from the limit.

This makes me think whether we actually need both request and limit ... do we really know how to utilize the available memory outside of request? For JVM it might be complicated, for the disk casche the OS will take care of it and we do not need Kubernetes.
