### ISSUE TITLE
Add memory and CPU requests and limits to Topic Controller deployment

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi#327]
The Topic Controller should have memory and CPU limits and requests. These should be set in both YAML files for direct deployment as well as used when deploying TC from CC. 

In the case ... do we need them configurable? Might be needed if someone wants to play with it somewhere in Minishift where requesting memory and CPU might cause issues.

**Comment by tombentley** [comment]
Still to do: Setting them in the yaml files.
