### ISSUE TITLE
Make it possible to configure JVM heap memory etc. for Kafka, Zookeeper and Kafka Connect

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi#328]
We should make it possible to fine tune the memory aspects of the JVM for Kafka, Kafka connect and Zookeeper.

As part of this task we should probably first investigate what are the options which should be configurable and what their relation is to memory request / limits. My assumption is that max heap size for Kafka brokers is the minimum needed. But might be more.

**Comment by tombentley** [comment]
The `kafka-server-start.sh` script has a `KAFKA_HEAP_OPTS` env var, defaulting to `"-Xmx1G -Xms1G"`. The zookeeper script has the same env var, with half those defaults. The [Kafka docs](https://kafka.apache.org/documentation/#java) say LinkedIn use (at least at the time of writing):

```
-Xmx6g -Xms6g -XX:MetaspaceSize=96m -XX:+UseG1GC
-XX:MaxGCPauseMillis=20 -XX:InitiatingHeapOccupancyPercent=35 -XX:G1HeapRegionSize=16M
-XX:MinMetaspaceFreeRatio=50 -XX:MaxMetaspaceFreeRatio=80
```

but that's obviously optimized for their use case and on bare metal.

[Confluent suggest](https://docs.confluent.io/current/kafka/deployment.html#memory) there's nothing to be gained from heaps bigger than about 5g, and that that would be suitable for machines with 32+g.

**Comment by tombentley** [comment]
The KAFKA_HEAP_OPTS used for the connect script defaults to `"-Xms256M -Xmx2G"`, so unlike Kafka has different initial and maximum heaps. Should we just slavishly reflect this inconsistency in the ConfigMaps, I wonder, with the connect CM supporting two configs, but the Kafka and ZK ones supporting only one?

**Comment by scholzj** [comment]
I don't know ... I'm fine with setting the same `-Xms` and `-Xmx` for all. It might make the configuration easier and mean that we have less to explain in docu.
