### ISSUE TITLE
java.net.NoRouteToHostException: No route to host

### ISSUE THREAD

**Issue by maropak** [strimzi/strimzi#336]
Hi,
I have received 

_WARN Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.NoRouteToHostException: No route to host
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
        at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)_

When I wanted take topics list from Kafka docker container using 

./kafka-topics.sh --list --zookeeper 172.30.28.101:2181
where 172.30.28.101 is MY_CLUSTER_KAFKA_PORT_9091_TCP_ADDR

In my-cluster-kafka-0 I have in logs 

_ERROR [KafkaApi-0] Number of alive brokers '1' does not meet the required replication factor '3' for the offsets topic (configured via 'offsets.topic.replication.factor'). This error can be ignored if the cluster is starting up and not all brokers are up yet._

Because my openshift instance has only one node (but in ephemeral-template.yaml I have set KAFKA_NODE_COUNT=3) - **is at least 3 nodes required ?**

Previously I also set vertx.disableFileCPResolving=true, because I had exception during kafka/zookeeper start , so maybe it cause problem ?

_Exception in thread "main" java.lang.IllegalStateException: Failed to create cache dir
	at io.vertx.core.impl.FileResolver.setupCacheDir(FileResolver.java:299)
	at io.vertx.core.impl.FileResolver.<init>(FileResolver.java:92)
	at io.vertx.core.impl.VertxImpl.<init>(VertxImpl.java:185)
	at io.vertx.core.impl.VertxImpl.<init>(VertxImpl.java:144)
	at io.vertx.core.impl.VertxImpl.<init>(VertxImpl.java:140)
	at io.vertx.core.impl.VertxFactoryImpl.vertx(VertxFactoryImpl.java:34)
	at io.vertx.core.Vertx.vertx(Vertx.java:82)
	at io.strimzi.controller.topic.Main.deploy(Main.java:38)
	at io.strimzi.controller.topic.Main.run(Main.java:33)
	at io.strimzi.controller.topic.Main.main(Main.java:26)_

Thanks for help

**Comment by scholzj** [comment]
> When I wanted take topics list from Kafka docker container using
> 
> ./kafka-topics.sh --list --zookeeper 172.30.28.101:2181
> where 172.30.28.101 is MY_CLUSTER_KAFKA_PORT_9091_TCP_ADDR

`kafka-topics.sh` is connecting to Zookeeper. So you have to supply an IP address of the Zookeeper service (Should be something like `MY_CLUSTER_ZOOKEEPER_PORT_2181_TCP_ADDR`). You should be also able to use the DNS - `my-cluster-zookeeper:2181`.

> In my-cluster-kafka-0 I have in logs
> 
> ERROR [KafkaApi-0] Number of alive brokers '1' does not meet the required replication factor '3' for the offsets topic (configured via 'offsets.topic.replication.factor'). This error can be ignored if the cluster is starting up and not all brokers are up yet.
> 
> Because my openshift instance has only one node (but in ephemeral-template.yaml I have set KAFKA_NODE_COUNT=3) - is at least 3 nodes required ?

You can run only one node Kafka cluster (at least for some playing it should be fine). But the KAfka configuration contains some parameters for configuring the replication for the internal topics (such as offsets) as well as default config. And if you run only a single Kafka node, the replication factor cannot be set to 3 - because that requires at least 3 nodes.

So you have to go to the `my-cluster` config map and change these options. It is controllerd by these options:
```
KAFKA_DEFAULT_REPLICATION_FACTOR: "1"
KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
```

You should set all of them to 1.

> Previously I also set vertx.disableFileCPResolving=true, because I had exception during kafka/zookeeper start , so maybe it cause problem ?

I never saw this one. Could you provide us a full log when it happened?

**Comment by maropak** [comment]
Thanks for quick response :)
In 1)
I should notice that 2181 is zookeeper port, my oversight - sorry for problem
In 2)
After changes flags to 1 in config map problem is solved and I can publish/subcribe
In 3)
Exception appeared when zookeper/kafka pod was starting, it could not start and all I saw in logs was 

_Exception in thread "main" java.lang.IllegalStateException: Failed to create cache dir
at io.vertx.core.impl.FileResolver.setupCacheDir(FileResolver.java:299)
at io.vertx.core.impl.FileResolver.(FileResolver.java:92)
at io.vertx.core.impl.VertxImpl.(VertxImpl.java:185)
at io.vertx.core.impl.VertxImpl.(VertxImpl.java:144)
at io.vertx.core.impl.VertxImpl.(VertxImpl.java:140)
at io.vertx.core.impl.VertxFactoryImpl.vertx(VertxFactoryImpl.java:34)
at io.vertx.core.Vertx.vertx(Vertx.java:82)
at io.strimzi.controller.topic.Main.deploy(Main.java:38)
at io.strimzi.controller.topic.Main.run(Main.java:33)
at io.strimzi.controller.topic.Main.main(Main.java:26)_

**I have one additional question, how you connect to cluster from outside openshift ? As I know usually route or service with externalIPs and type: LoadBalancer is used** 

Thanks a lot for help

**Comment by scholzj** [comment]
> I have one additional question, how you connect to cluster from outside openshift ? As I know usually route or service with externalIPs and type: LoadBalancer is used

Sorry, we currently don't support this. But it is on our roadmap, we will get to it sooner or later.

**Comment by scholzj** [comment]
@tombentley @ppatierno It looks like the Vert.x exception is from Topic Controller which you know better than me. Could you have a look?

**Comment by maropak** [comment]
Thanks for help.

Agree,
When I received exception during cluster-controller start I added 

VertxOptions options = new VertxOptions().setFileResolverCachingEnabled(false);
        System.setProperty("vertx.disableFileCPResolving", "true");
        Vertx vertx = Vertx.vertx(options);

In io.strimzi.controller.cluster.Main

and the same later during topic-controller start -  io.strimzi.controller.topic.Main

**Comment by tombentley** [comment]
It looks like vertx is not able to create `./.vertx/file-cache-${UUID}` for some new UUID. I assume this is a file permissions thing. If so, we can set system property `vertx.cacheDirBase` to somewhere writeable and it should work.

**Comment by ppatierno** [comment]
I had this problem in the past deploying Vert.x application on OpenShift but the current Docker image should prevent this one. It's related to the permissions that Vert.x app doesn't have in order to create content in a ".vertx" folder. It's really strange that it's happened now. I'm using it without problem.

**Comment by ppatierno** [comment]
@tombentley the following line [here](https://github.com/strimzi/java-docker-base/blob/master/scripts/launch_java.sh) should already deal with it : 

```
JAVA_OPTS="${JAVA_OPTS} -Dvertx.cacheDirBase=/tmp -Djava.security.egd=file:/dev/./urandom"
```

the `-Dvertx.cacheDirBase=/tmp `

**Comment by ppatierno** [comment]
Running the 0.2.0 version I have no problems with the topic-controller.
@maropak do you have more info about that ? are you using 0.2.0 ?

**Comment by maropak** [comment]
I'm using current master, but can switch to 0.2.0 and check there.
I will check master with -Dvertx.cacheDirBase=/tmp and let you know.

Thanks for help

**Comment by maropak** [comment]
Checked with -Dvertx.cacheDirBase=/tmp and master code and is working fine now 
If you want I can try with 0.2.0 and without JAVA_OPTS change.
If this is the same code like in master I will close issue.
Thanks a lot :)

**Comment by maropak** [comment]
Additional information which can be useful 
I'm using as base docker image redhat7 with jdk:1.8.0_131, not your FROM strimzi/java-base:8-3.

**Comment by ppatierno** [comment]
This explain why the Vert.x parameter is missing so the exception you provided here. I think that we can close this issue now, or ?

**Comment by maropak** [comment]
Of course, I will close, 
thanks once again :)
