### ISSUE TITLE
Automated testing

### ISSUE THREAD

**Issue by tombentley** [strimzi/strimzi#34]
We need automated tests for the configurations we're publishing. At a basic level, we should know that the deployments to OpenShift and Kubernetes actually work and don't produce errors, but we also need system-level testing with failure scenarios. https://fabric8.io/guide/testing.html might be a good place to start.

**Comment by scholzj** [comment]
I never used Arquilian but the link you posted looks quite good. I was originally for a start thinking only about some simple tests written using Bash and [Bats](https://github.com/sstephenson/bats). But your suggestion might be better ;-).

**Comment by scholzj** [comment]
@tombentley Hmm, funny enough ... we discussed Arquilian already in October :-).

BTW: I think you can close this issue when you merge the Smoke Tests.
