### ISSUE TITLE
System tests should be named *IT not *Test

### ISSUE THREAD

**Issue by tombentley** [strimzi/strimzi#345]
Although they are system tests, they "more like" integration tests, and naming them like this means `mvn verify -DskipITs` will run checkstyle, compile, run the unit tests, and run findbugs without running any of the (slow) integration tests.

**Comment by tombentley** [comment]
@serrss @asorokhtey this would be great to do when it is convenient for you, it would make it so much easier for run just the unit tests.

**Comment by serrss** [comment]
@tombentley @asorokhtey  It seems like a good idea to rename ST in order to be able to filter tests by type.
