### ISSUE TITLE
Add "Download" link to landing page

### ISSUE THREAD

**Issue by gunnarmorling** [strimzi/strimzi#356]
It took me a while to figure that the info is under "Releases", I was looking for a "Download Strimzi" link.

**Comment by gunnarmorling** [comment]
Yeah, it's more clear now. You might even consider to name that section just "Download" and drop the "/ Releases" part.

In terms of which downloads to offer, one question is for how long to prominently show all earlier versions. E.g. you might just show the current one on the landing page (as that's the one you want people to grab), and show all earlier ones on a separate page named "archive", "earlier releases" or similar.

It's the same for docs. What we have done there for Hibernate is to show an overlay on earlier docs versions (e.g. see https://docs.jboss.org/hibernate/validator/5.4/reference/en-US/html_single/), so people are aware of the fact that a newer one is available, also if e.g. Google sent them to that earlier doc version.

**Comment by scholzj** [comment]
I updated the website to contain standalone pages for all downloads / relases and docu. The main page now contains links only for the latest. I think this issue can be closed.
