### ISSUE TITLE
Topic ConfigMap example is missing strimzi.io/cluster label

### ISSUE THREAD

**Issue by donovanmuller** [strimzi/strimzi#407]
I'm following the [Documentation](http://strimzi.io/docs/0.3.0) for 0.3.0 for OpenShift, using the supplied example commands (no manual deploys) and using the example ConfigMap for a Topic [here (4.4 Example)](http://strimzi.io/docs/0.3.0/#_example) and the Topic does not get created.

Only after looking at the `STRIMZI_CONFIGMAP_LABELS` environment did I realise that I needed the `strimzi.io/cluster` label as well. I then read [this (2.5.3 Topic ConfigMap)](http://strimzi.io/docs/0.3.0/#_topic_configmap) about Cluster Controller vs. manual deploy and saw:

```
When the Topic Controller is deployed manually the strimzi.io/cluster label is not necessary.
``` 

However, the example ConfigMap is missing this label (which assumes manual deploy).

Perhaps there could be a further note or reminder above the example ConfigMap to avoid any future misunderstandings? Or perhaps just default to `strimzi.io/cluster: my-cluster` to fit with the example? Or I should just read more thoroughly 😄

**Comment by scholzj** [comment]
Thanks for raising this. This should be now fixed in the master documentation and will be released together with 0.4.0.
