### ISSUE TITLE
Include `ps` in the images?

### ISSUE THREAD

**Issue by tombentley** [strimzi/strimzi#88]
I noticed that the images currently lack `ps`. This can make life slightly harder if you have to `oc exec -ti bash -li` into the nodes (you have to poke around in `/proc` instead), and also means that the `(kafka|zookeeper)-stop-server.sh` scripts wouldn't work (not that they're used). Is it worth installing `procps-ng`?

**Comment by scholzj** [comment]
Any examples what would you use `ps` for? Just curious ...

**Comment by tombentley** [comment]
@scholzj I wanted to see the command line args of the kafka connect JVM. I could have done this using `/proc`, as I said, but `ps` is the first thing I reach for.

**Comment by scholzj** [comment]
@tombentley Yeah, that makes sense.

**Comment by scholzj** [comment]
This has been fixed with #197 .
