### ISSUE TITLE
Define the Pod Management Policy

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi#93]
Currently, out stateful sets use the default `OrderedReady` `podManagementPolicy` for both Kafka and Zookeeper. 

`OrderedReady` means that the pods will be started one by one as they become ready. And deleted one by one. This can cause the startup to take longer (because of the readiness initial delay etc.) and shutdown to take longer (waiting for each broker to shutdown etc.). Using a `Parallel` policy would start and shutdown the stateful sets faster.

However, this policy applies also to scale ups and scale downs. There the `OrderedReady` would take it through multiple *rebalancing* stages where as `Parallel` would do it in one big step. Again the `Parallel` could be much faster. However in big scale downs it can cause some data loss: imagine running 6 Kafka replicas and scaling down to 3 ... without proper use of rack IDs etc. it can easily be that some topics will have replicas only on the 3 pods which will be taken down and the data will be lost. This can be probably workaround by scaling down always by 1 pod (through the future controller) but starting / stopping / scaling up in big steps.

It seems a bit unfortunate that Kubernetes do not allow specifying different policy for each of these phases.

**Comment by tombentley** [comment]
> It seems a bit unfortunate that Kubernetes do not allow specifying different policy for each of these phases.

It might be worth checking if such work is already in the pipeline, and if not we could propose it.

**Comment by scholzj** [comment]
The way I addressed this in the cluster controller so far:
* Use the `Parallel` policy as default
* Scale up using the parallel policy (i.e. start multiple images at the same time)
* Scale down one by one - e.g. scale down from 6 to 3 pods is done in smaller steps ... 6-> 5 -> 4 -> 3 and basically overrides the parallel policy.

The scale down should be probably improved by interacting with Kafka to make sure that the data are properly replicated (i.e. there are no under replicated topics between the small steps). But it should solve this problem.

**Comment by scholzj** [comment]
This seems to be addressed in the cluster controller and should be closed.
